### ISSUE TITLE
Buy function

### ISSUE THREAD

**Issue by claudiosantos92** [dogancana/futbot#1]
there is no Buy function on this? :/

**Comment by dogancana** [comment]
I will implement it in couple of weeks when I have a free weekend.
First buy option will be more like invest feature. It'll read player prices from futbin and try to buy them for cheap. Then you can combine it with auto-sell to make profit

**Comment by claudiosantos92** [comment]
cool!
an autobidder could be good too

**Comment by dogancana** [comment]
So, when you'd have an autobidder, would you set a maximum price for specific player and try to get him under that price?
And if that's the case, are you buying him for profit or for your squad or SBC?

**Comment by claudiosantos92** [comment]
Could be for all those things

**Comment by claudiosantos92** [comment]
For the first question, yes
Bid him to get him cheaper, yes
