### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by raminhz90** [dogancana/futbot#18]
i get this error every time and the extension is built and active in chrome

`500 get /club?sort=desc&type=player&start=0&count=100 undefined Session not copied!. First load Fut Web App with extension undefined`

**Comment by dogancana** [comment]
If extension works properly, you should see fut web app's title change to '(Futbot) FUT Web App!'. Can you confirm that?

**Comment by raminhz90** [comment]
Yes that change is taking place

**Comment by dogancana** [comment]
So, extension loads correct. This means there is an issue with extension compilation or your configuration.

If extension would send session information to server, In the server logs, you would see a message like 
```
auth
XXXXX-XXXXX-XXXXX-XXXXX
undefined
```
If you don't see this message, either extension is broken or you are authenticating from outside of europe and didn't configure auth endpoint properly.

You need to open dev tools on fut web app. It'll try to stop you from debugging. Just deactivate break points and press play icon. Then go to network tab and search for a link like this: `utas.external.s2.fut.ea.com/ut/auth`. If you have s3 or s1, you'll need to change the target auth endpoint. If you have s2, you should check console for possible javascript errors from extension

**Comment by raminhz90** [comment]
i did that

the address was `https://utas.external.s3.fut.ea.com/ut/game/fifa20`

i changed it in . env file and restarted the server
reloaded the web app but nothing changed

then i rebuilt the extension but still nothing

**Comment by dogancana** [comment]
I see the issue, extension doesnt read the env file. I'll post a fix tonight. In the meantime you can change all 's2's to 's3' in /ui/src/content/auth.js
After changing and rebuilding, it should work fine
