### ISSUE TITLE
Chrome extension doesn't work already due to the change of FUT Web APP

### ISSUE THREAD

**Issue by stupidchen** [dogancana/futbot#2]
I try to install the extension and run bot server, I found the extension never send the authorization data to bot server.

After debugging I found FUT Web APP encapsulates something like XMLHttpRequest thus the AJAX interceptor of extension doesn't work anymore:

```
UTHttpRequest.prototype.send = function send() {
    if (this._http.readyState > XMLHttpRequest.UNSENT && this._http.readyState < XMLHttpRequest.DONE)
        utils.Debug.Assert(!1, "Attempted to send an HTTP request when it is in the middle of sending.");
    else if (this._http.readyState === XMLHttpRequest.DONE && this.reset(),
    utils.JS.isEmpty(this._url))
        utils.Debug.Assert(!1, "Attempted to send an HTTP request when URL is not set.");
    else {
        var url = this._url + this._urlVariables;
        this._http.open(this._requestType, url, !0),
        this._setDefaultHeaders();
        for (var headers = this._requestHeaders.slice(); headers.length > 0; ) {
            var t = headers.pop();
            this._http.setRequestHeader(t.name, t.value)
        }
        this._cache || this._http.setRequestHeader("Cache-Control", "no-cache"),
        this._timeout > 0 && (this._http.timeout = this._timeout),
        this._http.onreadystatechange = this._onStateChange.bind(this),
        this._requestBody && this._requestType !== enums.HTTPRequestMethod.DELETE ? this._http.send(this._requestBody) : this._http.send()
    }
}
```

Are there any solution about the interceptor?

**Comment by dogancana** [comment]
Just checking this code it seems like they overwrite extension's interceptor code. I'll look into it today

**Comment by dogancana** [comment]
I just checked the extension (I was not using for a while now), everything works fine on latest master. 
Can you try to to run yarn start with node v9 and try again?
And Page title should be changed to (Futbot) Fut Web App! as an indication of script is properly loaded

**Comment by stupidchen** [comment]
> I just checked the extension (I was not using for a while now), everything works fine on latest master.
> Can you try to to run yarn start with node v9 and try again?
> And Page title should be changed to (Futbot) Fut Web App! as an indication of script is properly loaded

Thanks for your reply.  I tried to rebuild the extension and start the server with node v9.11.0 but it also doesn't work. The page title had already changed but the server log didn't show and message about the session post request. Are there any other requirements such as Chrome version?

**Comment by dogancana** [comment]
No, chrome would auto update itself. It should be fine.
But try to debug from chrome itself. When you go to fut web app, just open dev tools, go to network tab and filter for 'auth'. You should see couple of request to localhost:9999

If it doesn't work:
1- clear node modules in root and under /ui
2- switch node version to 9, npm version to 5
3- npm install in root and in /ui
4- npm start in root
5- npm run dev in ui
6- Delete extension
7- load extension from ui/build

if this doesn't work again, I can put a prebuilt extension to repository. Maybe something is wrong in dependencies

**Comment by stupidchen** [comment]
> No, chrome would auto update itself. It should be fine.
> But try to debug from chrome itself. When you go to fut web app, just open dev tools, go to network tab and filter for 'auth'. You should see couple of request to localhost:9999
> 
> If it doesn't work:
> 1- clear node modules in root and under /ui
> 2- switch node version to 9, npm version to 5
> 3- npm install in root and in /ui
> 4- npm start in root
> 5- npm run dev in ui
> 6- Delete extension
> 7- load extension from ui/build
> 
> if this doesn't work again, I can put a prebuilt extension to repository. Maybe something is wrong in dependencies

I rebuilt the ui and found the interceptor did work. But the scrapAuthData wasn't called during the loading of Web APP. And I found only one request related to scrapAuthData possibly, its request URL is:

```
https://utas.external.s3.fut.ea.com/ut/auth?sku_c=fut19
```

Should I change the intercept target of scrapAuthData from 'https://utas.external.s2.fut.ea.com/ut/auth' to 'https://utas.external.s3.fut.ea.com/ut/auth'?

**Comment by dogancana** [comment]
Ah, it makes sense. Yeah you should.
It's in two places: 
- ui/src/content/auth.js (2 times)
- lib/api/fut-api.ts

I'll try to get this url dynamic for future problems

EDIT: all .s2. => .s3.

**Comment by stupidchen** [comment]
> Ah, it makes sense. Yeah you should.
> It's in two places:
> 
> * ui/src/content/auth.js (2 times)
> * lib/api/fut-api.ts
> 
> I'll try to get this url dynamic for future problems
> 
> EDIT: all .s2. => .s3.

By the way I found 4 compile errors when the server starting:

```
TSError: ⨯ Unable to compile TypeScript:
lib/trader/trade-utils.ts(35,35): error TS2339: Property '0' does not exist on type '[]'.
lib/trader/trade-utils.ts(43,24): error TS2532: Object is possibly 'undefined'.
lib/trader/trade-utils.ts(43,31): error TS2339: Property '0' does not exist on type '[]'.
lib/trader/trade-utils.ts(67,9): error TS2739: Type 'Price' is missing the following properties from type 'Prices': pc, xbox, ps
```

So I changed the type of some variables in lib/trader/trade-utils.ts and lib/player/player-service.ts and lib/api/futbin-api.ts. And then the server can start. Are these errors caused by the version of dependencies?

**Comment by dogancana** [comment]
Might be the case. I didn't lock the dependencies since, it's not a super serious project :) I'd appreciate a PR with your changes though. 
So everything works fine now?

**Comment by stupidchen** [comment]
> Might be the case. I didn't lock the dependencies since, it's not a super serious project :) I'd appreciate a PR with your changes though.
> So everything works fine now?

After the replacement and rebuild, both the extension and server runs well. Thanks for your reply again!

P.S. I will create a PR about the type errors. Nice works bro!

**Comment by Denist79** [comment]
Hi,

I am using windows to do this but i am stuck at this.

TSError: ? Unable to compile TypeScript:
lib/trader/trade-utils.ts(34,35): error TS2493: Tuple type '[]' of length '0' ha
s no element at index '0'.
lib/trader/trade-utils.ts(42,24): error TS2532: Object is possibly 'undefined'.
lib/trader/trade-utils.ts(42,31): error TS2493: Tuple type '[]' of length '0' ha
s no element at index '0'.

Thanks.

**Comment by Denist79** [comment]
at createTSError (C:\futbot\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (C:\futbot\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (C:\futbot\node_modules\ts-node\src\index.ts:558:11)
    at Module.m._compile (C:\futbot\node_modules\ts-node\src\index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\futbot\node_m
odules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dogancana** [comment]
I will check it in this weekend 👍

**Comment by dogancana** [comment]
I actually just checked it. Remove some optimizations of webpack, which was causing a weird issue related to creating vendor.js file. Master branch should be good now. I can't test in a windows machine, but it should just work fine. Can you try @Denist79 ?

**Comment by Denist79** [comment]
I Tried. Server starts and then when i try to access the list players this is the error i get.

C:\futbot>yarn dev
yarn run v1.15.2
$ nodemon
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\futbot\lib/**/*
[nodemon] starting `yarn start`
$ ts-node --inspect=5858 lib/app.ts
2019-05-04T04:37:31.617Z [FUTBOT] info: Express server listening on port 9999
Running CORS Anywhere on 0.0.0.0:9998
2019-05-04T04:38:55.576Z [FUTBOT] info: https://utas.external.s2.fut.ea.com/ut/game/fifa19/club?sort=desc&type=player&start=0&count=100
2019-05-04T04:38:55.579Z [FUTBOT] error: [undefined] undefined : undefined
(node:13452) UnhandledPromiseRejectionWarning: Error: Session not copied!. First load Fut Web App with extension
    at new ApiError (C:\futbot\lib\api\api.ts:82:7)
    at Object.<anonymous> (C:\futbot\lib\api\api-interceptors.ts:55:15)
    at step (C:\futbot\lib\api\api-interceptors.ts:32:23)
    at Object.next (C:\futbot\lib\api\api-interceptors.ts:13:53)
    at C:\futbot\lib\api\api-interceptors.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\futbot\lib\api\api-interceptors.ts:3:12)
    at C:\futbot\lib\api\api-interceptors.ts:51:47
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by Denist79** [comment]
When i close the app with the x button i get this error.

[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting child process
[nodemon] starting `yarn start`
$ ts-node --inspect=5858 lib/app.ts
2019-05-04T04:44:17.000Z [FUTBOT] info: Express server listening on port 9999
Running CORS Anywhere on 0.0.0.0:9998
error Command failed with exit code 3221225786.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dogancana** [comment]
Please follow README.md carefully. When server starts, you should also open the fifa web app with the chrome extension, Chrome extension will copy your session data to server, So server can make requests on behalf of you.

**Comment by Denist79** [comment]
> Please follow README.md carefully. When server starts, you should also open the fifa web app with the chrome extension, Chrome extension will copy your session data to server, So server can make requests on behalf of you.

Looks like the .env file is my issue. I am from Australia and maybe the .env config is not working in my region. When i try to open the link it throws that error. Where do you get the .env information from.

Thanks.

**Comment by dogancana** [comment]
@Denist79 It's probably one of below:
https://utas.external.s1.fut.ea.com/ut/game/fifa19
https://utas.external.s3.fut.ea.com/ut/game/fifa19

You can always open developer tools, network tab in official fut web api and check address for one of those. Once you find yours, just update your config
