### ISSUE TITLE
error auth

### ISSUE THREAD

**Issue by yusuuf68** [dogancana/futbot#23]
when i start the server i get this error
(FUTBOT) info:
auth
"XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
undefined

**Comment by raminhz90** [comment]
this is not an error
this is how it logs your auth token

**Comment by dogancana** [comment]
Logs are generally not errors, Application crashes and wrong prices are

**Comment by yusuuf68** [comment]
okay sorry 
but how i can fix that

**Comment by dogancana** [comment]
There is nothing to fix. There will be lot's of logs like that
