### ISSUE TITLE
error on futbin

### ISSUE THREAD

**Issue by raminhz90** [dogancana/futbot#24]
i'm getting error 404 on futbin

i tried to visit the page with chrome but 404 again

`error: [FUTBIN]: 404 get https://www.futbin.com/20/players?page=0&sort=likes&order=desc&_price=1000-5000 undefined Request failed with status code 404`

also player prices also sending valid requests always returns nothing i checked those requests with chrome and python requests and both returned prices

i don't understand node but i guess there is something about the way requests are sent that makes futbin not answer them

**Comment by dogancana** [comment]
Are you on ps4 or xbox?

**Comment by raminhz90** [comment]
I'm on Xbox

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dogancana** [comment]
Yeah, this is know issue. I cannot try it with ps4 and xbox, hence the error
It'll be fixed in next release
