### ISSUE TITLE
Min market buy now and market samples didn't work on extension

### ISSUE THREAD

**Issue by juanrodicio** [dogancana/futbot#26]
It's always set on 0.
![image](https://user-images.githubusercontent.com/22750959/67144205-7683fb80-f274-11e9-844a-dc3f4c760931.png)

**Comment by dogancana** [comment]
Are you on PS4 for xbox? If so, this issue will be fixed in next release

**Comment by juanrodicio** [comment]
I'm on PC

**Comment by dogancana** [comment]
I see the same error,
Will look into this
