### ISSUE TITLE
Bot doesn't buy anything in 2h

### ISSUE THREAD

**Issue by juanrodicio** [dogancana/futbot#28]
First of all, thank you for share this project. I really appreciate it.
This is the result jobs from my bot after 2 hours running.
![image](https://user-images.githubusercontent.com/22750959/67148232-9b409900-f29d-11e9-8fad-3ef44cc39ccf.png)
Using LowPlayer or GoodAuction doesn't work for me. GoodAuction got targets but always fail to do de bid. Any ideas?

**Comment by dogancana** [comment]
I think this is related to profit margin. It was set to 20% by default and it doesn't work well.
I was just working on a change which will make it possible to set it via .env file.
You can set it there.

It also depends on time of the day. 

And good auction job logic has room for improvement. I'll rewrite most of it tomorrow. Then we can retry these in next week and see what happens

**Comment by juanrodicio** [comment]
I tried after with the LowPlayer and it works just adding more budget... But it appears to calculate wrong sell price giving place to situations like this.
![image](https://user-images.githubusercontent.com/22750959/67151320-d0141680-f2c4-11e9-82ba-0d84ac9c48ac.png)

**Comment by dogancana** [comment]
This is a trade of if choose to check all the prices from market. And futbin rarely makes mistakes on most liked players. But anyway, I'm planning to put a configurable 'ONLY_USE_SAFE_PRICES' parameter in future.

**Comment by dogancana** [comment]
I'm closing this issue as, you can set your own PROFIT_MARGIN in .env now.
