### ISSUE TITLE
Cant read manifest file in stable version 

### ISSUE THREAD

**Issue by Lejmassu** [dogancana/futbot#30]
Thanks for taking your time. Cant seem to add the extension to chrome when trying to use the stable version. It say it cant read the manifest. When I edit the manifest file and save it as json instead as a javascript it said: 
Manifest is not valid JSON. Line: 1, column: 1, Unexpected token.

Any thoughts?

**Comment by dogancana** [comment]
You are trying to load wrong manifest file. Which version did you use?

**Comment by Lejmassu** [comment]
futbot-1.3.2\futbot-1.3.2\extension\src

This version and tried loading the manifest file in src map.

**Comment by dogancana** [comment]
Please try 1.3.1
I'm testing something with 1.3.2 version
in 1.3.1, when you unzip, just select extension while loading

**Comment by Lejmassu** [comment]
Alright, thanks, managed to make it work
