### ISSUE TITLE
prp in futbin xbox queries won't work

### ISSUE THREAD

**Issue by dogancana** [dogancana/futbot#31]
**Describe the bug**
While getting low player invest targets from futbin, the query with xbox prp value gives 404

**To Reproduce**
1. Start server with xbox profile
2. See auth token log
3. Execute task /invest/low-players
4. See the error 404 on setup targets

**Expected behavior**
Should remove prp value on xbox

**Desktop (please complete the following information):**
 - OS: all
 - Platform: Xbox
 - 1.4.0.

**Comment by hpbuniat** [comment]
Fixed :)
