### ISSUE TITLE
how to start service on macos?

### ISSUE THREAD

**Issue by orange5276** [dogancana/futbot#32]
I have load the extension by chrome, click the extension , Your fut endpoint: is blank.
I double clicked the server-macos then....
xxMBP:~ xx$ /Users/xx/Downloads/futbot/server-macos ; exit;
.env file not found. Copy .env.local file as .env file and restart.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by dogancana** [comment]
Macos starts the server in a different directory than futboy. 
Open a terminal
cd /path/to/futbot
./server-macos

And extension reads your endpoint after sevond time. Just rrfresh the page and try again.

**Comment by orange5276** [comment]
thanks so much , i can start server now. 
but my endpoint is still blank , i will try again.

**Comment by dogancana** [comment]
It'll only show up after you login
