### ISSUE TITLE
Cannot get endpoint in extension

### ISSUE THREAD

**Issue by orange5276** [dogancana/futbot#34]
I followed all the steps described in https://github.com/dogancana/futbot                  done
I rebuilt the extension, removed the old one and loaded new one successfully.            done
I clicked to the extension and saw Futbot title with my endpoint properly set.              no
I set FUTBOT_FUT_API_ENDPOINT_OVERWRITE in .env file as shown from extension    no

I have tried both win and macos system. Chrome can success to load extension , then start services.
"Session not copied!. First load Fut Web App with extension undefined"
Clicked extension , but endpoint is always blank, i also cannot set .env
Tired many times and rrrefresh the page many times.

How i can solve the problem ,thanks again!

**Comment by orange5276** [comment]
Additional info, i also tired use Euro IP VPN want to active the .env endpoint set.
But i still failed....

**Comment by orange5276** [comment]
i have find solution! FUT have many website address, only https://www.fifplay.com/fut-web-app/ is ok.
https://www.easports.com/uk/fifa/ultimate-team/web-app/  extension cannot work!

**Comment by dogancana** [comment]
Ah, that makes sense
Can you try to use https://easports.com/fifa/ultimate-team/web-app
If it's forcing you to use uk one i need to make a change
