### ISSUE TITLE
Add max rating and amount for selling jobs

### ISSUE THREAD

**Issue by stupidchen** [dogancana/futbot#5]
I found simply calling `http://localhost:9999/trade-bot/start-selling` will trying to clear all items in trade pile and sold numbers of players (default: 10) of the club. It causes two problems:
* Sometimes user may not let the high rating player sold automatically (may make profit by selling in specific time)
* User cannot sell more players because there is no way to set the amount of the selling job

Thus there is a requirement to add two arguments for the api:
* max rating: Set the max rating of players which will be sold
* amount: Set the amount of sold players of the selling job

The expectation like this:
`http://localhost:9999/trade-bot/start-selling?maxRating=75&amount=100`

**Comment by stupidchen** [comment]
@dogancana 
I am working on it and hope you can review it. Thanks!

**Comment by dogancana** [comment]
Thanks for work. 
For selling high value players: I had this max rating feature but never pushed it. I'll push it now. 
For selling amount: I tested couple of times, for selling too many players but your account gets too many requests ban. And my idea of using this auto sell players feature is start the job before the night. With trade pile clear and reselling, you woke up to (50-100)+ sold players

**Comment by stupidchen** [comment]
> Thanks for work.
> For selling high value players: I had this max rating feature but never pushed it. I'll push it now.
> For selling amount: I tested couple of times, for selling too many players but your account gets too many requests ban. And my idea of using this auto sell players feature is start the job before the night. With trade pile clear and reselling, you woke up to (50-100)+ sold players

For selling amount: I think giving a optional amount will be a reasonable choice for some user. And you know there are some guys whose trade pile is always full (full of Toni Kroos) and they just want to sell some players in club for more coins...

**Comment by stupidchen** [comment]
@dogancana 
BTW, nice work for the new commit!
