### ISSUE TITLE
Chrome extension throws error (webpackJsonp_name_ is not defined)

### ISSUE THREAD

**Issue by dhondtlaurens** [dogancana/futbot#6]
Hi, i'm trying to get this working but when i load the extension. It keeps throwing following error: Uncaught ReferenceError: webpackJsonp_name_ is not defined @ js/inject.js:1 (anonymous function). I'v tried to fix this but no success so far...

**Comment by dogancana** [comment]
Hi,
It happens because of wrong node version. Can you use node 8 or 9 and try again? You should delete node modules in ui folder and reinstall/rebuild

**Comment by dhondtlaurens** [comment]
I used nvm to try with different node versions. Deleted all node modules and installed/build with following versions: 9.7.1 / 8.9.4 / 8.6.0 ... All still giving the same error. Could you provide us with the build folder or a packed version (.crx). Thanks!

**Comment by dhondtlaurens** [comment]
Alright, it works when running dev server. However, the server keeps replying with: Session not copied!. First load Fut Web App with extension... Is there another caveat i'm not seeing! :)

**Comment by dogancana** [comment]
Both extension and dev server should be running/loaded fine. What extension does is, reading your session token and send it to server. You can open dev tools and see if extension is trying to send a request to localhost:9999/auth. 
For extension to be able read your token, you have to either login or click to store. Both should work fine

**Comment by dhondtlaurens** [comment]
Alright, got it working... I had already changed the url's to s3... But on my account it's still s2... Thank you very much! This is great!
